// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zQuitSmoking.Repositories.ThinhTHP.Models;

public partial class ConsultationSessionNamHh
{
    public int ConsultationSessionNamHhid { get; set; }

    public int UserAccountId { get; set; }

    public int CoachId { get; set; }

    public DateTime SessionDate { get; set; }

    public int DurationMinutes { get; set; }

    public string SessionTopic { get; set; }

    public bool? IsCompleted { get; set; }

    public int? Rating { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual SystemUserAccount Coach { get; set; }

    public virtual ICollection<SessionFeedbackNamHh> SessionFeedbackNamHhs { get; set; } = new List<SessionFeedbackNamHh>();

    public virtual SystemUserAccount UserAccount { get; set; }
}