// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zQuitSmoking.Repositories.ThinhTHP.Models;

public partial class HealthMetricTrungDn
{
    public int HealthMetricTrungDnid { get; set; }

    public int SmokingRecordTrungDnid { get; set; }

    public DateTime? MetricDate { get; set; }

    public int? HeartRate { get; set; }

    public string BloodPressure { get; set; }

    public decimal? LungCapacity { get; set; }

    public int? StressLevel { get; set; }

    public bool? IsImproved { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual SmokingRecordTrungDn SmokingRecordTrungDn { get; set; }
}