// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zQuitSmoking.Repositories.ThinhTHP.Models;

public partial class NotificationThinhThp
{
    public int NotificationThinhThpid { get; set; }

    public string NotificationType { get; set; }

    public string Message { get; set; }

    public string ScheduleType { get; set; }

    public DateTime TriggerTime { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int PriorityLevel { get; set; }

    public virtual ICollection<UserNotificationThinhThp> UserNotificationThinhThps { get; set; } = new List<UserNotificationThinhThp>();
}