// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zQuitSmoking.Repositories.ThinhTHP.Models;

public partial class PlanStageVietHq
{
    public int PlanStageVietHqid { get; set; }

    public int QuitPlanVietHqid { get; set; }

    public string StageName { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public int TargetReduction { get; set; }

    public int? AchievedReduction { get; set; }

    public bool? IsCompleted { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual QuitPlanVietHq QuitPlanVietHq { get; set; }
}