// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zQuitSmoking.Repositories.ThinhTHP.Models;

public partial class QuitPlanVietHq
{
    public int QuitPlanVietHqid { get; set; }

    public int UserAccountId { get; set; }

    public string PlanName { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime ExpectedEndDate { get; set; }

    public string Reason { get; set; }

    public int InitialCigarettesPerDay { get; set; }

    public int TargetCigarettesPerDay { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ICollection<PlanStageVietHq> PlanStageVietHqs { get; set; } = new List<PlanStageVietHq>();

    public virtual SystemUserAccount UserAccount { get; set; }
}