// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zQuitSmoking.Repositories.ThinhTHP.Models;

public partial class SmokingRecordTrungDn
{
    public int SmokingRecordTrungDnid { get; set; }

    public int UserAccountId { get; set; }

    public DateTime? RecordDate { get; set; }

    public int CigarettesPerDay { get; set; }

    public decimal CostPerPack { get; set; }

    public int FrequencyPerDay { get; set; }

    public bool? IsCurrent { get; set; }

    public string Notes { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ICollection<HealthMetricTrungDn> HealthMetricTrungDns { get; set; } = new List<HealthMetricTrungDn>();

    public virtual SystemUserAccount UserAccount { get; set; }
}