// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zQuitSmoking.Repositories.ThinhTHP.Models;

public partial class SystemUserAccount
{
    public int UserAccountId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string EmployeeCode { get; set; }

    public int RoleId { get; set; }

    public string RequestCode { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ApplicationCode { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<ConsultationSessionNamHh> ConsultationSessionNamHhCoaches { get; set; } = new List<ConsultationSessionNamHh>();

    public virtual ICollection<ConsultationSessionNamHh> ConsultationSessionNamHhUserAccounts { get; set; } = new List<ConsultationSessionNamHh>();

    public virtual ICollection<QuitPlanVietHq> QuitPlanVietHqs { get; set; } = new List<QuitPlanVietHq>();

    public virtual ICollection<SmokingRecordTrungDn> SmokingRecordTrungDns { get; set; } = new List<SmokingRecordTrungDn>();

    public virtual ICollection<UserNotificationThinhThp> UserNotificationThinhThps { get; set; } = new List<UserNotificationThinhThp>();

    public virtual ICollection<UserSubscriptionQuanNh> UserSubscriptionQuanNhs { get; set; } = new List<UserSubscriptionQuanNh>();
}