// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zQuitSmoking.Repositories.ThinhTHP.Models;

public partial class UserSubscriptionQuanNh
{
    public int UserSubscriptionQuanNhid { get; set; }

    public int UserAccountId { get; set; }

    public int MembershipPackageQuanNhid { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public decimal PaymentAmount { get; set; }

    public DateTime PaymentDate { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionId { get; set; }

    public bool IsPaid { get; set; }

    public string Status { get; set; }

    public virtual MembershipPackageQuanNh MembershipPackageQuanNh { get; set; }

    public virtual SystemUserAccount UserAccount { get; set; }
}