// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace zQuitSmoking.Repositories.ThinhTHP.Models;

public partial class UserNotificationThinhThp
{
    public int UserNotificationThinhThpid { get; set; }

    public int UserAccountId { get; set; }

    public int NotificationThinhThpid { get; set; }

    public DateTime? SentDate { get; set; }

    public bool IsRead { get; set; }

    public string Response { get; set; }

    public string Status { get; set; }

    public int? AttemptCount { get; set; }

    public DateTime? LastAttemptDate { get; set; }

    public virtual NotificationThinhThp NotificationThinhThp { get; set; }

    public virtual SystemUserAccount UserAccount { get; set; }
}